---
- name: Ensure rsync is present (not strictly required now, but useful)
  apt:
    name: rsync
    state: present
    update_cache: true
  become: true

- name: Ensure web root
  file:
    path: "{{ web_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  become: true

- name: Download WordPress archive
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    mode: '0644'
  become: true

# Кладём файлы прямо в web_root (+ убираем верхнюю папку wordpress/)
- name: Unarchive WordPress directly into web root
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: "{{ web_root }}"
    remote_src: true
    extra_opts:
      - --strip-components=1
  become: true

- name: Ensure uploads directory
  file:
    path: "{{ web_root }}/wp-content/uploads"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  become: true

- name: Deploy wp-config.php
  template:
    src: wp-config.php.j2
    dest: "{{ web_root }}/wp-config.php"
    owner: www-data
    group: www-data
    mode: '0640'
  become: true

- name: Set ownership for web root
  file:
    path: "{{ web_root }}"
    state: directory
    recurse: true
    owner: www-data
    group: www-data
  become: true
