---
- name: Download WordPress archive
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    mode: '0644'
  become: true

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    remote_src: true
  become: true

- name: Sync WordPress to web root
  synchronize:
    src: /tmp/wordpress/
    dest: "{{ web_root }}/"
    delete: no
    recursive: yes
  become: true

- name: Ensure uploads directory
  file:
    path: "{{ web_root }}/wp-content/uploads"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  become: true

- name: Deploy wp-config.php
  template:
    src: wp-config.php.j2
    dest: "{{ web_root }}/wp-config.php"
    owner: www-data
    group: www-data
    mode: '0640'
  become: true

- name: Set ownership for web root
  file:
    path: "{{ web_root }}"
    state: directory
    recurse: true
    owner: www-data
    group: www-data
  become: true
