---
- name: Install MySQL server and client
  apt:
    name:
      - mysql-server
      - mysql-client
    state: present
    update_cache: true
  become: true

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: true
  become: true

# Для Ubuntu по умолчанию root с auth_socket. Команды ниже выполняются с sudo.
- name: Create database for WordPress if not exists
  shell: |
    mysql -u root -e "CREATE DATABASE IF NOT EXISTS \`{{ db_name }}\` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
  args:
    executable: /bin/bash
  become: true

- name: Create user for WordPress (native password) and grant
  shell: |
    mysql -u root -e "CREATE USER IF NOT EXISTS '{{ db_user }}'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ db_password }}';"
    mysql -u root -e "GRANT ALL PRIVILEGES ON \`{{ db_name }}\`.* TO '{{ db_user }}'@'localhost'; FLUSH PRIVILEGES;"
  args:
    executable: /bin/bash
  become: true
